# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 磨叽熊猫
subtitle:
description:
keywords:
author: cocosongying
language:
  - zh-CN
timezone:
favicon:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://cocosongying.github.io/hexo
root: /hexo
#permalink: :year/:month/:day/:title/
permalink_defaults:

# abbrlink config
abbrlink:
  alg: crc16 #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# 更改 permalink 值
permalink: p/:abbrlink.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
plugin:
  - hexo-generator-feed
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
## Themes: https://hexo.io/themes/
theme: material-x

# 页脚社交信息
social:
  - icon: fas fa-envelope
    url: mailto:cocosongying@gmail.com
  - icon: fab fa-github
    url: https://github.com/cocosongying
  - icon: fab fa-weibo
    url: https://weibo.com/cocosongying
  - icon: fas fa-rss
    url: /atom.xml
footer: '一花一世界，一叶一追寻。一曲一场叹，一生为一人。'

# 导航栏，建议以/结尾。
menu:
  - name: home
    icon: fas fa-home
    url: https://cocosongying.github.com/
  - name: blogs
    icon: fas fa-rss
    url: /
  - name: archives
    icon: fas fa-archive
    url: archives/

# 侧边栏小部件
widgets:
  - widget: author
    avatar: https://cocosongying.github.io/img/author.jpg
    jinrishici: 一生一世一双人
    social: true
  - widget: toc
  - widget: plain
    icon: fas fa-bullhorn
    title: 注意啦～
    body: '本站使用 [Material X](https://xaoxuu.com/wiki/material-x/) 作为主题，喜欢这个主题的朋友可以阅读文档进行安装哦，超喜欢的话还可以安利给身边的朋友哦～'
  - widget: category
  - widget: tagcloud
  - widget: list
    icon: fas fa-tools
    title: 实用工具
    rows:
      - name: Carbon
        desc: 线上代码图片
        icon: fas fa-feather-alt
        url: https://carbon.now.sh/
      - name: Draw.io
        desc: 线上流程图
        icon: fas fa-feather-alt
        url: https://www.draw.io/
      - name: Markdown Plus
        desc: 线上编辑器
        icon: fas fa-feather-alt
        url: https://mdp.tylingsoft.com/
  - widget: list
    icon: fas fa-medal
    title: 精选项目
    more:
      icon: fas fa-arrow-right
      url: https://github.com/cocosongying/
    rows:
      - name: ParkingQuerySystem
        desc: Android
        icon: fas fa-cube
        url: https://github.com/cocosongying/ParkingQuerySystem
  - widget: list
    icon: fas fa-link
    title: 特别链接
    rows:
      - name: 关于我
        icon: fas fa-comment-dots
        url: about/
#  - widget: related_posts

#是否开启打赏功能
donate: true
donate_wechat: https://cocosongying.github.io/img/wechatpay.jpeg
#打赏文案
donate_message: 欣赏此文？求鼓励，求支持！

#share:
#  - id: weibo
#    name: 微博
#    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
#  - id: qrcode
#    name: QRcode
#    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png

live2d:
  enable: true
  scriptFrom: local
  model: 
    use: live2d-widget-model-shizuku #模型选择
  display: 
    position: right  #模型位置
    width: 150       #模型宽度
    height: 220      #模型高度
  mobile: 
    show: false      #是否在手机端显示

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/cocosongying/hexo.git
  branch: master
